In [28]:
#read file 
import pandas as pd
filepath = "pollution_us_2000_2016.csv"
us_pollution_data = pd.read_csv(filepath)
us_pollution_data.columns

Index(['Unnamed: 0', 'State Code', 'County Code', 'Site Num', 'Address',
       'State', 'County', 'City', 'Date Local', 'NO2 Units', 'NO2 Mean',
       'NO2 1st Max Value', 'NO2 1st Max Hour', 'NO2 AQI', 'O3 Units',
       'O3 Mean', 'O3 1st Max Value', 'O3 1st Max Hour', 'O3 AQI', 'SO2 Units',
       'SO2 Mean', 'SO2 1st Max Value', 'SO2 1st Max Hour', 'SO2 AQI',
       'CO Units', 'CO Mean', 'CO 1st Max Value', 'CO 1st Max Hour', 'CO AQI'],
      dtype='object')

In [17]:
#Create Year column. which we will use to group the data by year.
Date_data = []
for i in us_pollution_data['Date Local']:
    date = i.split("-")
    year= date[0]
    Date_data.append(year)
us_pollution_data['Year'] = Date_data

#clean data by dropping rows with null values.
us_pollution_data_clean = us_pollution_data.dropna(how='any')

In [29]:
#Create a collection of columns of interest 
Chem_Columns = us_pollution_data_clean[['State', 'Date Local', 'Year','NO2 Units', 'NO2 Mean', 'O3 Units', 'O3 Mean','SO2 Units', 'SO2 Mean', 'CO Units', 'CO Mean']]
Chem_Columns.head()

,State,Date Local,Year,NO2 Units,NO2 Mean,O3 Units,O3 Mean,SO2 Units,SO2 Mean,CO Units,CO Mean
0,Arizona,2000-01-01,2000,Parts per billion,19.041667,Parts per million,0.022500,Parts per billion,3.000000,Parts per million,0.878947
1,Arizona,2000-01-02,2000,Parts per billion,22.958333,Parts per million,0.013375,Parts per billion,1.958333,Parts per million,1.066667
2,Arizona,2000-01-03,2000,Parts per billion,38.125000,Parts per million,0.007958,Parts per billion,5.250000,Parts per million,1.762500
3,Arizona,2000-01-04,2000,Parts per billion,40.260870,Parts per million,0.014167,Parts per billion,7.083333,Parts per million,1.829167
4,Arizona,2000-01-05,2000,Parts per billion,48.450000,Parts per million,0.006667,Parts per billion,8.708333,Parts per million,2.700000

In [31]:
test = Chem_Columns.groupby(['Year', 'State']).mean()
# test.pivot(index='State', columns='Year', values='')

                            NO2 Mean   O3 Mean  SO2 Mean   CO Mean
Year State
2000 Arizona               26.492344  0.023664  2.297970  0.746075
     California            17.580980  0.023675  1.730039  0.647508
     Colorado              14.902469  0.017066  2.113657  0.615031
     District Of Columbia  22.725717  0.017567  8.172178  1.178786
     Florida               12.453038  0.026261  1.983244  0.726884
     Illinois              26.437457  0.017105  6.099496  0.706236
     Indiana               15.287580  0.029782  7.299264  0.875499
     Kansas                 9.703852  0.029726  0.952126  0.756692
     Kentucky              12.660981  0.028916  4.770384  0.178344
     Louisiana             17.346074  0.023756  3.664487  0.758775
     Michigan              22.682065  0.023367  5.420799  0.280681
     Missouri              16.872750  0.027761  4.167004  0.524458
     New Jersey            20.527509  0.020263  6.294039  0.586453
     New York              23.152019  0.021248  7.197875  0.464648
     North Carolina        15.173355  0.034652  3.690656  0.619122
     Oklahoma               4.761760  0.037350  0.850058  0.047210
     Pennsylvania          16.128973  0.024542  5.173892  0.303847
     Texas                 16.331339  0.024600  2.767254  0.437538
     Virginia              17.918191  0.022604  9.071010  0.647606
2001 Arizona               22.741468  0.021632  1.674073  0.652423
     California            17.758503  0.024845  1.822917  0.625402
     Colorado              25.783401  0.016376  2.424493  0.630548
     District Of Columbia  24.474311  0.020936  6.700384  1.077945
     Florida               12.362754  0.024173  1.154526  0.640209
     Illinois              22.356840  0.020868  5.501072  0.593802
     Indiana               14.947844  0.032153  3.275512  0.383134
     Kansas                10.594909  0.027978  1.003458  0.336699
     Kentucky              12.547682  0.030233  4.072306  0.131677
     Louisiana             17.359239  0.022978  3.694475  0.827924
     Massachusetts         24.048434  0.019194  5.924173  0.300087
...                              ...       ...       ...       ...
2016 Colorado              23.623820  0.020989  1.015169  0.453770
     Delaware              13.771055  0.025159  0.843855  0.284438
     District Of Columbia  12.460650  0.031057  0.988631  0.256361
     Florida                5.492869  0.029213  0.398801  0.574539
     Georgia               11.935326  0.019770  0.298054  0.315240
     Illinois              10.374432  0.025014  0.956746  0.310079
     Indiana               13.857478  0.026542  0.404344  0.245990
     Iowa                   5.994895  0.030609  0.197278  0.211936
     Kansas                11.582273  0.022840  1.097587  0.251962
     Louisiana             12.911402  0.026846  1.122964  0.234943
     Maine                  6.556909  0.028197  0.345396  0.300699
     Maryland               9.200686  0.027409  0.745955  0.250659
     Massachusetts         15.829273  0.023563  0.691639  0.270368
     Missouri              12.485847  0.023046  1.131472  0.324271
     Nevada                17.420815  0.022641  0.392133  0.322915
     New Hampshire          4.294246  0.031651  0.834677  0.212214
     New York              17.847473  0.023972  1.067515  0.295042
     North Carolina         7.471214  0.029335  0.245527  0.248812
     North Dakota           4.671010  0.025868  0.256340  0.192902
     Ohio                   9.760795  0.025508  1.679378  0.278759
     Oklahoma               8.125385  0.025688  1.504453  0.277756
     Pennsylvania           7.500877  0.027863  1.067559  0.097009
     Rhode Island           7.740605  0.032334  0.379558  0.237469
     South Carolina         9.312171  0.029761  0.244968  0.159291
     Tennessee              1.011065  0.037987  0.146649  0.189711
     Texas                 10.357079  0.026515  0.331293  0.226866
     Utah                  31.515873  0.013308  0.675595  0.513974
     Virginia              10.320663  0.022908  0.566670  0.291597
     Washington            14.999242  0.015436  0.202633  0.280371
     Wyoming                3.425564  0.039149 -0.036313  0.095296

[496 rows x 4 columns]

In [30]:
# us_pollution_data_clean = us_pollution_data_clean.reset_index()
# us_pollution_data_clean